"Read and parse BibTex entry."

import string
import unicodedata

import bibtexparser

MONTHS = {
    "jan": 1,
    "january": 1,
    "feb": 2,
    "february": 2,
    "mar": 3,
    "march": 3,
    "apr": 4,
    "april": 4,
    "may": 5,
    "jun": 6,
    "june": 6,
    "jul": 7,
    "july": 7,
    "aug": 8,
    "august": 8,
    "sep": 9,
    "september": 9,
    "oct": 10,
    "october": 10,
    "nov": 11,
    "november": 11,
    "dec": 12,
    "december": 12,
}


# From data found at https://www.ctan.org/tex-archive/support/utf2any/maps
LATEX_TO_UTF8 = {
    "~": "\u00a0",
    "!`": "\u00a1",
    "\\textcent{}": "\u00a2",
    "\\pounds{}": "\u00a3",
    "\\textcurrency{}": "\u00a4",
    "\\textyen{}": "\u00a5",
    "\\textbrokenbar{}": "\u00a6",
    "\\S{}": "\u00a7",
    "\\textasciidieresis{}": "\u00a8",
    "\\copyright{}": "\u00a9",
    "\\textordfeminine{}": "\u00aa",
    "\\guillemotleft{}": "\u00ab",
    "\\textlnot{}": "\u00ac",
    "-": "\u2011",
    "\\textregistered{}": "\u00ae",
    "\\textmacron{}": "\u203e",
    "\\textdegree{}": "\u00b0",
    "\\textpm{}": "\u00b1",
    "\\texttwosuperior{}": "\u00b2",
    "\\textthreesuperior{}": "\u00b3",
    "\\textasciiacute{}": "\u00b4",
    "\\textmu{}": "\u00b5",
    "\\P{}": "\u00b6",
    "\\textperiodcentered{}": "\u2027",
    "\\c{": "\u00b8",
    "\\textonesuperior{}": "\u00b9",
    "\\textordmasculine{}": "\u00ba",
    "\\guillemotright{}": "\u00bb",
    "\\ensuremath{{}^1\\!/\\!_4}": "\u00bc",
    "\\ensuremath{{}^1\\!/\\!_2}": "\u00bd",
    "\\ensuremath{{}^3\\!/\\!_4}": "\u00be",
    "?`": "\u00bf",
    "\\`A": "\u00c0",
    "\\'A": "\u00c1",
    "\\^A": "\u00c2",
    "\\~A": "\u00c3",
    '\\"A': "\u00c4",
    "\\AA{}": "\u00c5",
    "\\AE{}": "\u00c6",
    "\\c{C}": "\u00c7",
    "\\`E": "\u00c8",
    "\\'E": "\u00c9",
    "\\^E": "\u00ca",
    '\\"E': "\u00cb",
    "\\`I": "\u00cc",
    "\\'I": "\u00cd",
    "\\^I": "\u00ce",
    '\\"I': "\u00cf",
    "\\DH{}": "\u00d0",
    "\\~N": "\u00d1",
    "\\`O": "\u00d2",
    "\\'O": "\u00d3",
    "\\^O": "\u00d4",
    "\\~O": "\u00d5",
    '\\"O': "\u00d6",
    "\\texttimes{}": "\u00d7",
    "\\O{}": "\u00d8",
    "\\O": "\u00d8",
    "\\`U": "\u00d9",
    "\\'U": "\u00da",
    "\\^U": "\u00db",
    '\\"U': "\u00dc",
    "\\'Y": "\u00dd",
    "\\TH{}": "\u00de",
    "\\ss{}": "\u00df",
    "\\`a": "\u00e0",
    "\\'a": "\u00e1",
    "\\^a": "\u00e2",
    "\\~a": "\u00e3",
    '\\"a': "\u00e4",
    "\\aa{}": "\u00e5",
    "\\ae{}": "\u00e6",
    "\\c{c}": "\u00e7",
    "\\`e": "\u00e8",
    "\\'e": "\u00e9",
    "\\^e": "\u00ea",
    '\\"e': "\u00eb",
    "\\`{\\i}": "\u00ec",
    "\\'{\\i}": "\u00ed",
    "\\^{\\i}": "\u00ee",
    '\\"{\\i}': "\u00ef",
    "\\dh{}": "\u00f0",
    "\\~n": "\u00f1",
    "\\`o": "\u00f2",
    "\\'o": "\u00f3",
    "\\^o": "\u00f4",
    "\\~o": "\u00f5",
    '\\"o': "\u00f6",
    "\\textdiv{}": "\u00f7",
    "\\o{}": "\u00f8",
    "\\o": "\u00f8",
    "\\`u": "\u00f9",
    "\\'u": "\u00fa",
    "\\^u": "\u00fb",
    '\\"u': "\u00fc",
    "\\'y": "\u00fd",
    "\\th{}": "\u00fe",
    '\\"y': "\u00ff",
    "\\=A": "\u0100",
    "\\=a": "\u0101",
    "\\u{A}": "\u0102",
    "\\u{a}": "\u0103",
    "\\textpolhook{A}": "\u0104",
    "\\textpolhook{a}": "\u0105",
    "\\'C": "\u0106",
    "\\'c": "\u0107",
    "\\^C": "\u0108",
    "\\^c": "\u0109",
    "\\.C": "\u010a",
    "\\.c": "\u010b",
    "\\v{C}": "\u010c",
    "\\v{c}": "\u010d",
    "\\v{D}": "\u010e",
    "\\v{d}": "\u010f",
    "\\DJ{}": "\u0110",
    "\\dj{}": "\u0111",
    "\\=E": "\u0112",
    "\\=e": "\u0113",
    "\\u{E}": "\u0114",
    "\\u{e}": "\u0115",
    "\\.E": "\u0116",
    "\\.e": "\u0117",
    "\\textpolhook{E}": "\u0118",
    "\\textpolhook{e}": "\u0119",
    "\\v{E}": "\u011a",
    "\\v{e}": "\u011b",
    "\\^G": "\u011c",
    "\\^g": "\u011d",
    "\\u{G}": "\u011e",
    "\\u{g}": "\u011f",
    "\\.G": "\u0120",
    "\\.g": "\u0121",
    "\\c{G}": "\u0122",
    "\\c{g}": "\u0123",
    "\\^H": "\u0124",
    "\\^h": "\u0125",
    "\\textcrh{}": "\u0127",
    "\\~I": "\u0128",
    "\\~{\\i}": "\u0129",
    "\\=I": "\u012a",
    "\\={\\i}": "\u012b",
    "\\u{I}": "\u012c",
    "\\u{\\i}": "\u012d",
    "\\textpolhook{I}": "\u012e",
    "\\textpolhook{\\i}": "\u012f",
    "\\.I": "\u0130",
    "\\i{}": "\u0131",
    "IJ": "\u0132",
    "ij": "\u0133",
    "\\^J": "\u0134",
    "\\^{\\j}": "\u0135",
    "\\c{K}": "\u0136",
    "\\c{k}": "\u0137",
    "\\'L": "\u0139",
    "\\'l": "\u013a",
    "\\c{L}": "\u013b",
    "\\c{l}": "\u013c",
    "\\v{L}": "\u013d",
    "\\v{l}": "\u013e",
    "L\\ensuremath{\\cdot}": "\u013f",
    "l\\ensuremath{\\cdot}": "\u0140",
    "\\L{}": "\u0141",
    "\\l{}": "\u0142",
    "\\'N": "\u0143",
    "\\'n": "\u0144",
    "\\c{N}": "\u0145",
    "\\c{n}": "\u0146",
    "\\v{N}": "\u0147",
    "\\v{n}": "\u0148",
    "'n": "\u0149",
    "\\NG{}": "\u014a",
    "\\ng{}": "\u014b",
    "\\=O": "\u014c",
    "\\=o": "\u014d",
    "\\u{O}": "\u014e",
    "\\u{o}": "\u014f",
    "\\H{O}": "\u0150",
    "\\H{o}": "\u0151",
    "\\OE{}": "\u0152",
    "\\oe{}": "\u0153",
    "\\'R": "\u0154",
    "\\'r": "\u0155",
    "\\c{R}": "\u0156",
    "\\c{r}": "\u0157",
    "\\v{R}": "\u0158",
    "\\v{r}": "\u0159",
    "\\'S": "\u015a",
    "\\'s": "\u015b",
    "\\^S": "\u015c",
    "\\^s": "\u015d",
    "\\c{S}": "\u015e",
    "\\c{s}": "\u015f",
    "\\v{S}": "\u0160",
    "\\v{s}": "\u0161",
    "\\c{T}": "\u0162",
    "\\c{t}": "\u0163",
    "\\v{T}": "\u0164",
    "\\v{t}": "\u0165",
    "\\~U": "\u0168",
    "\\~u": "\u0169",
    "\\=U": "\u016a",
    "\\=u": "\u016b",
    "\\u{U}": "\u016c",
    "\\u{u}": "\u016d",
    "\\r{U}": "\u016e",
    "\\r{u}": "\u016f",
    "\\H{U}": "\u0170",
    "\\H{u}": "\u0171",
    "\\textpolhook{U}": "\u0172",
    "\\textpolhook{u}": "\u0173",
    "\\^W": "\u0174",
    "\\^w": "\u0175",
    "\\^Y": "\u0176",
    "\\^y": "\u0177",
    '\\"Y': "\u0178",
    "\\'Z": "\u0179",
    "\\'z": "\u017a",
    "\\.Z": "\u017b",
    "\\.z": "\u017c",
    "\\v{Z}": "\u017d",
    "\\v{z}": "\u017e",
    "\\textcrb{}": "\u0180",
    "\\textit{f}": "\u0192",
    "\\textgamma{}": "\u0263",
    "\\texthvlig{}": "\u0195",
    "\\ipabar{I}{.6ex}{1.1}{}{}": "\u0197",
    "\\textbarl{}": "\u019a",
    "\\textcrlambda{}": "\u019b",
    "\\ipabar{Z}{.7ex}{1.1}{}{}": "\u01b5",
    "\\ipabar{z}{.5ex}{1.1}{}{}": "\u01b6",
    "\\textrevyogh{}": "\u01b9",
    "\\textcrinvglotstop{}": "\u01be",
    "\\textpipe{}": "\u01c0",
    "\\textdoublepipe{}": "\u01c1",
    "\\textdoublebarpipe{}": "\u01c2",
    "!": "\u01c3",
    "D\\v{Z}": "\u01c4",
    "D\\v{z}": "\u01c5",
    "d\\v{z}": "\u01c6",
    "LJ": "\u01c7",
    "Lj": "\u01c8",
    "lj": "\u01c9",
    "NJ": "\u01ca",
    "Nj": "\u01cb",
    "nj": "\u01cc",
    "\\v{A}": "\u01cd",
    "\\v{a}": "\u01ce",
    "\\v{I}": "\u01cf",
    "\\v{\\i}": "\u01d0",
    "\\v{O}": "\u01d1",
    "\\v{o}": "\u01d2",
    "\\v{U}": "\u01d3",
    "\\v{u}": "\u01d4",
    '\\={\\"U}': "\u01d5",
    '\\={\\"u}': "\u01d6",
    "\\'{\\\"U}": "\u01d7",
    "\\'{\\\"u}": "\u01d8",
    '\\v{\\"U}': "\u01d9",
    '\\v{\\"u}': "\u01da",
    '\\`{\\"U}': "\u01db",
    '\\`{\\"u}': "\u01dc",
    "\\textschwa{}": "\u0259",
    '\\={\\"A}': "\u01de",
    '\\={\\"a}': "\u01df",
    "\\={\\.A}": "\u01e0",
    "\\={\\.a}": "\u01e1",
    "\\={\\AE}": "\u01e2",
    "\\={\\ae}": "\u01e3",
    "\\v{G}": "\u01e6",
    "\\v{g}": "\u01e7",
    "\\v{K}": "\u01e8",
    "\\v{k}": "\u01e9",
    "\\textpolhook{O}": "\u01ea",
    "\\textpolhook{o}": "\u01eb",
    "\\={\\textpolhook{O}}": "\u01ec",
    "\\={\\textpolhook{o}}": "\u01ed",
    "\\v{\\textyogh}": "\u01ef",
    "\\v{\\j}": "\u01f0",
    "DZ": "\u01f1",
    "Dz": "\u01f2",
    "dz": "\u01f3",
    "\\'G": "\u01f4",
    "\\'g": "\u01f5",
    "\\'{\\AA}": "\u01fa",
    "\\'{\\aa}": "\u01fb",
    "\\'{\\AE}": "\u01fc",
    "\\'{\\ae}": "\u01fd",
    "\\'{\\O}": "\u01fe",
    "\\'{\\o}": "\u01ff",
    "\\textdoublegrave{A}": "\u0200",
    "\\textdoublegrave{a}": "\u0201",
    "\\textroundcap{A}": "\u0202",
    "\\textroundcap{a}": "\u0203",
    "\\textdoublegrave{E}": "\u0204",
    "\\textdoublegrave{e}": "\u0205",
    "\\textroundcap{E}": "\u0206",
    "\\textroundcap{e}": "\u0207",
    "\\textdoublegrave{I}": "\u0208",
    "\\textdoublegrave{\\i}": "\u0209",
    "\\textroundcap{I}": "\u020a",
    "\\textroundcap{\\i}": "\u020b",
    "\\textdoublegrave{O}": "\u020c",
    "\\textdoublegrave{o}": "\u020d",
    "\\textroundcap{O}": "\u020e",
    "\\textroundcap{o}": "\u020f",
    "\\textdoublegrave{R}": "\u0210",
    "\\textdoublegrave{r}": "\u0211",
    "\\textroundcap{R}": "\u0212",
    "\\textroundcap{r}": "\u0213",
    "\\textdoublegrave{U}": "\u0214",
    "\\textdoublegrave{u}": "\u0215",
    "\\textroundcap{U}": "\u0216",
    "\\textroundcap{u}": "\u0217",
    "\\textturna{}": "\u0250",
    "\\textscripta{}": "\u0251",
    "\\textturnscripta{}": "\u0252",
    "\\texthtb{}": "\u0253",
    "\\textopeno{}": "\u0254",
    "\\textctc{}": "\u0255",
    "\\textrtaild{}": "\u0256",
    "\\texthtd{}": "\u0257",
    "\\textreve{}": "\u0258",
    "\\textrhookschwa{}": "\u025a",
    "\\textepsilon{}": "\u025b",
    "\\textrevepsilon{}": "\u025c",
    "\\textrhookrevepsilon{}": "\u025d",
    "\\textcloserevepsilon{}": "\u025e",
    "\\textObardotlessj{}": "\u025f",
    "\\texthtg{}": "\u0260",
    "\\textipa{g}": "\u0261",
    "\\textscg{}": "\u0262",
    "\\textbabygamma{}": "\u0264",
    "\\textturnh{}": "\u0265",
    "\\texthth{}": "\u0266",
    "\\texththeng{}": "\u0267",
    "\\textbari{}": "\u0268",
    "\\textiota{}": "\u0269",
    "\\textsci{}": "\u026a",
    "\\textltilde{}": "\u026b",
    "\\textbeltl{}": "\u026c",
    "\\textrtaill{}": "\u026d",
    "\\textturnm{}": "\u026f",
    "\\textturnmrleg{}": "\u0270",
    "\\textltailm{}": "\u0271",
    "\\textltailn{}": "\u0272",
    "\\textrtailn{}": "\u0273",
    "\\textscn{}": "\u0274",
    "\\textbaro{}": "\u0275",
    "\\textscoelig{}": "\u0276",
    "\\textcloseomega{}": "\u0277",
    "\\textphi{}": "\u0278",
    "\\textturnr{}": "\u0279",
    "\\textturnlonglegr{}": "\u027a",
    "\\textturnrrtail{}": "\u027b",
    "\\textlonglegr{}": "\u027c",
    "\\textrtailr{}": "\u027d",
    "\\textfishhookr{}": "\u027e",
    "\\textscr{}": "\u0280",
    "\\textinvscr{}": "\u0281",
    "\\textrtails{}": "\u0282",
    "\\textesh{}": "\u0283",
    "\\textdoublebaresh{}": "\u0284",
    "\\textctesh{}": "\u0286",
    "\\textturnt{}": "\u0287",
    "\\textrtailt{}": "\u0288",
    "\\textbaru{}": "\u0289",
    "\\textupsilon{}": "\u028a",
    "\\textscriptv{}": "\u028b",
    "\\textturnv{}": "\u028c",
    "\\textturnw{}": "\u028d",
    "\\textturny{}": "\u028e",
    "\\textscy{}": "\u028f",
    "\\textrtailz{}": "\u0290",
    "\\textctz{}": "\u0291",
    "\\textyogh{}": "\u0292",
    "\\textctyogh{}": "\u0293",
    "\\textglotstop{}": "\u0294",
    "\\textrevglotstop{}": "\u0295",
    "\\textinvglotstop{}": "\u0296",
    "\\textstretchc{}": "\u0297",
    "\\textbullseye{}": "\u0298",
    "\\textscb{}": "\u0299",
    "\\textcloseepsilon{}": "\u029a",
    "\\texthtscg{}": "\u029b",
    "\\textsch{}": "\u029c",
    "\\textctj{}": "\u029d",
    "\\textturnk{}": "\u029e",
    "\\textscl{}": "\u029f",
    "\\texthtq{}": "\u02a0",
    "\\textbarglotstop{}": "\u02a1",
    "\\textbarrevglotstop{}": "\u02a2",
    "\\textdzlig{}": "\u02a3",
    "\\textdyoghlig{}": "\u02a4",
    "\\textdctzlig{}": "\u02a5",
    "\\texttslig{}": "\u02a6",
    "\\textteshlig{}": "\u02a7",
    "\\texttctclig{}": "\u02a8",
    "\\textsuperscript{h}": "\u02b0",
    "\\textsuperscript{\\texthth}": "\u02b1",
    "\\textsuperscript{j}": "\u02b2",
    "\\textsuperscript{r}": "\u02b3",
    "\\textsuperscript{\\textturnr}": "\u02b4",
    "\\textsuperscript{\\textturnrrtail}": "\u02b5",
    "\\textsuperscript{\\textinvscr}": "\u02b6",
    "\\textsuperscript{w}": "\u02b7",
    "\\textsuperscript{y}": "\u02b8",
    "\\textceltpal{}": "\u02b9",
    "\\textceltpal\\textceltpal{}": "\u02ba",
    "\\tone{55}": "\u02e5",
    "\\tone{44}": "\u02e6",
    "\\tone{33}": "\u02e7",
    "\\tone{22}": "\u02e8",
    "\\tone{11}": "\u02e9",
    "--": "\u2013",
    "---": "\u2014",
    "`": "\u2018",
    "'": "\u2019",
    "\\quotesinglbase{}": "\u201a",
    "``": "\u201c",
    "''": "\u201d",
    "\\quotedblbase{}": "\u201e",
    "\\dag{}": "\u2020",
    "\\ddag{}": "\u2021",
    "\\textbullet{}": "\u2022",
    ".": "\u2024",
    "..": "\u2025",
    "\\ldots{}": "\u2026",
    "\\textperthousand{}": "\u2030",
    "\\textpertenthousand{}": "\u2031",
    "\\ensuremath{\\prime}": "\u2032",
    "\\ensuremath{\\prime\\prime}": "\u2033",
    "\\ensuremath{\\prime\\prime\\prime}": "\u2034",
    "\\guilsinglleft{}": "\u2039",
    "\\guilsinglright{}": "\u203a",
    "\\textreferencemark{}": "\u203b",
    "!!": "\u203c",
    "\\textinterrobang{}": "\u203d",
    "\\textlquill{}": "\u2045",
    "\\textrquill{}": "\u2046",
    "\\euro{}": "\u20ac",
    "\\ensuremath{{}^a\\!/\\!_c}": "\u2100",
    "\\ensuremath{{}^a\\!/\\!_s}": "\u2101",
    "\\ensuremath{{}^c\\!/\\!_o}": "\u2105",
    "\\ensuremath{{}^c\\!/\\!_u}": "\u2106",
    "N\\textordmasculine{}": "\u2116",
    "\\textservicemark{}": "\u2120",
    "\\ensuremath{{}^\\mathrm{TEL}}": "\u2121",
    "\\texttrademark{}": "\u2122",
    "\\ensuremath{\\aleph}": "\u2135",
    "\\ensuremath{{}^1\\!/\\!_3}": "\u2153",
    "\\ensuremath{{}^2\\!/\\!_3}": "\u2154",
    "\\ensuremath{{}^1\\!/\\!_5}": "\u2155",
    "\\ensuremath{{}^2\\!/\\!_5}": "\u2156",
    "\\ensuremath{{}^3\\!/\\!_5}": "\u2157",
    "\\ensuremath{{}^4\\!/\\!_5}": "\u2158",
    "\\ensuremath{{}^1\\!/\\!_6}": "\u2159",
    "\\ensuremath{{}^5\\!/\\!_6}": "\u215a",
    "\\ensuremath{{}^1\\!/\\!_8}": "\u215b",
    "\\ensuremath{{}^3\\!/\\!_8}": "\u215c",
    "\\ensuremath{{}^5\\!/\\!_8}": "\u215d",
    "\\ensuremath{{}^7\\!/\\!_8}": "\u215e",
    "\\ensuremath{{}^1\\!/}": "\u215f",
    "I": "\u2160",
    "II": "\u2161",
    "III": "\u2162",
    "IV": "\u2163",
    "V": "\u2164",
    "VI": "\u2165",
    "VII": "\u2166",
    "VIII": "\u2167",
    "IX": "\u2168",
    "X": "\u2169",
    "XI": "\u216a",
    "XII": "\u216b",
    "L": "\u216c",
    "C": "\u216d",
    "D": "\u216e",
    "M": "\u216f",
    "i": "\u2170",
    "ii": "\u2171",
    "iii": "\u2172",
    "iv": "\u2173",
    "v": "\u2174",
    "vi": "\u2175",
    "vii": "\u2176",
    "viii": "\u2177",
    "ix": "\u2178",
    "x": "\u2179",
    "xi": "\u217a",
    "xii": "\u217b",
    "l": "\u217c",
    "c": "\u217d",
    "d": "\u217e",
    "m": "\u217f",
    "ff": "\ufb00",
    "fi": "\ufb01",
    "fl": "\ufb02",
    "ffi": "\ufb03",
    "ffl": "\ufb04",
}


def from_latex_to_utf8(value):
    "Clean up and convert string value from LaTeX notation to UTF-8 characters."
    value = " ".join(value.split())
    stack = []
    result = []
    for pos, c in enumerate(value):
        if c == "{":
            stack.append(pos)
        elif c == "}":
            if len(stack) == 1:
                item = value[stack[0] : pos + 1]
                # This kludge fixes a problem seen in BibTex from Paperpile.
                if item.startswith(r"{\v "):
                    item = r"{\v{" + item[4:] + "}"
                result.append(LATEX_TO_UTF8.get(item[1:-1], item))
            stack.pop()
        elif not stack:
            result.append(c)
    return "".join(result)


def parse(bibtex):
    result = []
    for entry in bibtexparser.loads(bibtex).entries:
        data = dict(
            authors=from_latex_to_utf8(entry.get("author", "")).split(" and "),
            type=entry.get("ENTRYTYPE") or constants.ARTICLE,
            year=int(entry["year"]),
        )
        result.append(data)
        if editors := from_latex_to_utf8(entry.get("editor", "")):
            data["editors"] = editors.split(" and ")
        for key, value in entry.items():
            if key in ("author", "editor", "ID", "ENTRYTYPE", "year"):
                continue
            data[key] = from_latex_to_utf8(value).strip()
        # Do some post-processing.
        # Change month into date; sometimes has day number.
        month = from_latex_to_utf8(data.pop("month", ""))
        parts = month.split("~")
        if len(parts) == 2 and parts[1]:
            month = MONTHS[parts[1].strip().casefold()]
            day = int("".join([c for c in parts[0] if c in string.digits]))
            data["published"] = f'{entry["year"]}-{month:02d}-{day:02d}'
        elif len(parts) == 1 and parts[0]:
            month = MONTHS[parts[0].strip().casefold()]
            data["published"] = f'{entry["year"]}-{month:02d}-00'
        # Issue instead of number.
        try:
            data["issue"] = data.pop("number")
        except KeyError:
            pass
        # Change page numbers double dash to single dash.
        if pages := data.pop("pages", None):
            data["pages"] = pages.replace("--", "-")
        if abstract := data.pop("abstract", None):
            data["abstract"] = from_latex_to_utf8(" ".join(abstract.split()))
    return result


if __name__ == "__main__":
    import json

    bibtex = """@BOOK{Tuck2002-ma,
title = "Hobbes: A Very Short Introduction",
author = "Tuck, Richard",
publisher = "Oxford University Press",
address = "London, England",
series = "Very Short Introductions",
month =  dec,
year =  2002,
doi = "10.1093/actrade/9780192802552.001.0001",
isbn =  9780192802552,
language = "en"
}
    @BOOK{Boehm1999-cb,
title = "Hierarchy in the Forest. The Evolution of Egalitarian Behavior",
author = "Boehm, Christopher",
publisher = "Harvard University Press",
address = "London, England",
year =  1999,
isbn =  9780674006911,
language = "en"
}
@BOOK{Darwin2013-cv,
title = "The descent of man",
author = "Darwin, Charles",
publisher = "Wordsworth Editions",
address = "Ware, England",
series = "Wordsworth Classics of World Literature",
month =  "8~" # jul,
year =  2013,
isbn =  9781840226980,
language = "en"
}
@ARTICLE{Enright2017-ak,
title = "'To the victor go the spoils': Infants expect resources to align with dominance structures",
author = "Enright, Elizabeth A and Gweon, Hyowon and Sommerville, Jessica A",
journal = "Cognition",
publisher = "Elsevier",
volume =  164,
pages = "8--21",
abstract = "Previous research has found that within the first year of life infants possess rich knowledge about social structures (i.e., that some individuals are dominant over other individuals) as well as expectations about resource distributions (i.e., that resources are typically distributed equally to recipients). We investigated whether infants' expectations about resource distribution can be modulated by information about the dominance structure between the recipients. We first replicated the finding that infants attribute a stable dominance hierarchy to a pair of individuals when their goals conflicted and one individual yielded to the other (Expt. 1), and that this sensitivity is not driven by lower-level perceptual factors (Expt. 2). In Experiments 3-5, we tested our main hypothesis that infants' attention to equal and unequal distributions varies as a function of prior social dominance information. We first replicated and extended prior work by establishing that infants looked significantly longer to unequal than equal resource distributions when no prior information about dominance was provided about recipients (Expt. 3). Critically, following social dominance information, infants looked significantly longer to an equal distribution of resources than a distribution that favored the dominant individual (Expt. 4), and looked significantly longer when the submissive individual received more resources compared to when the dominant individual received more resources (Expts. 4 and 5). Together, these findings suggest that infants expect resources to align with social dominance structures.",
month =  "1~" # jul,
year =  2017,
keywords = "Inequality; Infant social cognition; Resource distributions; Social dominance",
doi = "10.1016/j.cognition.2017.03.008",
pmc = "PMC5839744",
pmid =  28346870,
issn = "0010-0277,1873-7838",
language = "en"
}
@ARTICLE{Kay2026-bb,
title = "Dated gene duplications elucidate the evolutionary assembly of eukaryotes",
author = "Kay, Christopher J and Spang, Anja and Szöllősi, Gergely J and Pisani, Davide and Williams, Tom A and Donoghue, Philip C J",
journal = "Nature",
publisher = "Springer Science and Business Media LLC",
volume =  650,
number =  8100,
pages = "129--140",
abstract = "The origin of eukaryotes was a formative but poorly understood event in the history of life. Current hypotheses of eukaryogenesis differ principally in the timing of mitochondrial endosymbiosis relative to the acquisition of other eukaryote novelties1. Discriminating among these hypotheses has been challenging, because there are no living lineages representative of intermediate steps within eukaryogenesis. However, many eukaryotic cell functions are contingent on genes that emerged from duplication events during eukaryogenesis2,3. Consequently, the timescale of these duplications can provide insights into the sequence of steps in the evolutionary assembly of the eukaryotic cell. Here we show, using a relaxed molecular clock4, that the process of eukaryogenesis spanned the Mesoarchaean to late Palaeoproterozoic eras. Within these constraints, we dated the timing of these gene duplications, revealing that the eukaryotic host cell already had complex cellular features before mitochondrial endosymbiosis, including an elaborated cytoskeleton, membrane trafficking, endomembrane, phagocytotic machinery and a nucleus, all between 3.0 and 2.25 billion years ago, after which mitochondrial endosymbiosis occurred. Our results enable us to reject mitochondrion-early scenarios of eukaryogenesis5, instead supporting a complexified-archaean, late-mitochondrion sequence for the assembly of eukaryote characteristics. Our inference of a complex archaeal host cell is compatible with hypotheses on the adaptive benefits of syntrophy6,7 in oceans that would have remained largely anoxic for more than a billion years8,9.",
month =  feb,
year =  2026,
doi = "10.1038/s41586-025-09808-z",
pmid =  41339551,
issn = "0028-0836,1476-4687",
language = "en"
}

    """
    for data in parse(bibtex):
        print(json.dumps(data, indent=2, ensure_ascii=False))
